// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2, arg3);
}

export function DeleteRun(arg1) {
  return window['go']['main']['App']['DeleteRun'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function GetPrivilegeStatus() {
  return window['go']['main']['App']['GetPrivilegeStatus']();
}

export function GetRunOutput(arg1) {
  return window['go']['main']['App']['GetRunOutput'](arg1);
}

export function GetToolDocs(arg1) {
  return window['go']['main']['App']['GetToolDocs'](arg1);
}

export function GetToolHealth() {
  return window['go']['main']['App']['GetToolHealth']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function GetWorkspaceByID(arg1) {
  return window['go']['main']['App']['GetWorkspaceByID'](arg1);
}

export function GetWorkspaceHistory(arg1) {
  return window['go']['main']['App']['GetWorkspaceHistory'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function RunToolStreaming(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunToolStreaming'](arg1, arg2, arg3, arg4);
}
