// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {tool} from '../models';

export function CreateWorkspace(arg1:string,arg2:string,arg3:string):Promise<main.Workspace>;

export function DeleteRun(arg1:number):Promise<void>;

export function DeleteToolExample(arg1:number):Promise<void>;

export function DeleteWorkspace(arg1:number):Promise<void>;

export function GetPrivilegeStatus():Promise<tool.PrivilegeInfo>;

export function GetRunOutput(arg1:number):Promise<string>;

export function GetToolDocs(arg1:string):Promise<main.ToolDocumentation>;

export function GetToolHealth():Promise<Array<tool.ToolHealth>>;

export function GetTools():Promise<Array<tool.ToolDef>>;

export function GetWorkspaceByID(arg1:number):Promise<main.Workspace>;

export function GetWorkspaceHistory(arg1:number):Promise<Array<main.CommandRun>>;

export function GetWorkspaces():Promise<Array<main.Workspace>>;

export function RunTool(arg1:number,arg2:string,arg3:string,arg4:Array<string>):Promise<tool.RunResult>;

export function RunToolStreaming(arg1:number,arg2:string,arg3:string,arg4:Array<string>):Promise<tool.StreamStartResult>;

export function SaveToolDocs(arg1:string,arg2:string):Promise<void>;

export function SaveToolExample(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function UpdateWorkspace(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
